[package]
name = "udp_acceptable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.4.7"
nix = "0.26.1"
futures = "0.3.25"

[dev-dependencies]
serial_test = "0.10.0"
